[rewrite_local]
^https:\/\/api\.wetalkapp\.com\/app\/queryBalanceAndBonus url script-request-header https://raw.githubusercontent.com/noxenys/loon/main/scripts/WeTalk_universal.js

[task_local]
20 8,20 * * * https://raw.githubusercontent.com/noxenys/loon/main/scripts/WeTalk_universal.js, tag=WeTalk签到, enabled=true

[MITM]
hostname = api.wetalkapp.com
